/**
 * Tarot deck seed data - 78 cards in Portuguese (pt-BR)
 *
 * Structure:
 * - Major Arcana: 22 cards (0-21)
 * - Minor Arcana: 56 cards (22-77)
 *   - Wands (Paus): 14 cards
 *   - Cups (Copas): 14 cards
 *   - Swords (Espadas): 14 cards
 *   - Pentacles (Ouros): 14 cards
 *
 * Each suit has: Ace, 2-10, Page (Pajem), Knight (Cavaleiro), Queen (Rainha), King (Rei)
 */

export interface TarotCardSeed {
  code: string;
  name: string;
  arcana: "major" | "minor";
  suit: "wands" | "cups" | "swords" | "pentacles" | "none";
  cardIndex: number;
  keywordsUpright: string[];
  keywordsReversed: string[];
  descriptionUpright: string;
  descriptionReversed: string;
}

// ============================================================
// MAJOR ARCANA (Arcanos Maiores)
// ============================================================

const majorArcana: TarotCardSeed[] = [
  {
    code: "major_00_the_fool",
    name: "O Louco",
    arcana: "major",
    suit: "none",
    cardIndex: 0,
    keywordsUpright: ["novos começos", "inocência", "espontaneidade", "espírito livre"],
    keywordsReversed: ["imprudência", "risco excessivo", "ingenuidade", "falta de direção"],
    descriptionUpright: "O Louco representa novos começos e um salto de fé. Ele encoraja você a abraçar o desconhecido com coração aberto e espírito aventureiro.",
    descriptionReversed: "Quando invertido, O Louco pode indicar imprudência ou decisões precipitadas. É hora de avaliar os riscos antes de agir.",
  },
  {
    code: "major_01_the_magician",
    name: "O Mago",
    arcana: "major",
    suit: "none",
    cardIndex: 1,
    keywordsUpright: ["manifestação", "habilidade", "poder pessoal", "ação"],
    keywordsReversed: ["manipulação", "truques", "talentos não utilizados", "engano"],
    descriptionUpright: "O Mago representa o poder de transformar ideias em realidade. Você tem todas as ferramentas necessárias para alcançar seus objetivos.",
    descriptionReversed: "Quando invertido, O Mago alerta sobre manipulação ou uso inadequado de talentos. Cuidado com ilusões e falsas promessas.",
  },
  {
    code: "major_02_the_high_priestess",
    name: "A Sacerdotisa",
    arcana: "major",
    suit: "none",
    cardIndex: 2,
    keywordsUpright: ["intuição", "mistério", "sabedoria interior", "subconsciente"],
    keywordsReversed: ["segredos", "desconexão", "ruído mental", "informação oculta"],
    descriptionUpright: "A Sacerdotisa convida você a confiar em sua intuição e explorar seu mundo interior. Há sabedoria escondida esperando ser descoberta.",
    descriptionReversed: "Quando invertida, pode indicar que você está ignorando sua voz interior ou que segredos podem estar afetando a situação.",
  },
  {
    code: "major_03_the_empress",
    name: "A Imperatriz",
    arcana: "major",
    suit: "none",
    cardIndex: 3,
    keywordsUpright: ["fertilidade", "abundância", "natureza", "nutrição"],
    keywordsReversed: ["bloqueio criativo", "dependência", "negligência", "sufocamento"],
    descriptionUpright: "A Imperatriz simboliza fertilidade, abundância e conexão com a natureza. É um período favorável para criatividade e crescimento.",
    descriptionReversed: "Quando invertida, pode indicar bloqueio criativo ou dependência excessiva dos outros. Cuide de si mesmo primeiro.",
  },
  {
    code: "major_04_the_emperor",
    name: "O Imperador",
    arcana: "major",
    suit: "none",
    cardIndex: 4,
    keywordsUpright: ["autoridade", "estrutura", "controle", "figura paterna"],
    keywordsReversed: ["tirania", "rigidez", "falta de disciplina", "dominação"],
    descriptionUpright: "O Imperador representa estrutura, autoridade e controle. É hora de estabelecer ordem e assumir responsabilidades.",
    descriptionReversed: "Quando invertido, pode indicar abuso de poder, rigidez excessiva ou falta de limites saudáveis.",
  },
  {
    code: "major_05_the_hierophant",
    name: "O Hierofante",
    arcana: "major",
    suit: "none",
    cardIndex: 5,
    keywordsUpright: ["tradição", "espiritualidade", "educação", "conformidade"],
    keywordsReversed: ["rebelião", "subversão", "novas abordagens", "liberdade pessoal"],
    descriptionUpright: "O Hierofante representa tradições, ensinamentos espirituais e valores compartilhados. Busque orientação de fontes confiáveis.",
    descriptionReversed: "Quando invertido, pode indicar necessidade de questionar tradições ou encontrar seu próprio caminho espiritual.",
  },
  {
    code: "major_06_the_lovers",
    name: "Os Enamorados",
    arcana: "major",
    suit: "none",
    cardIndex: 6,
    keywordsUpright: ["amor", "harmonia", "escolhas", "valores"],
    keywordsReversed: ["desequilíbrio", "desarmonia", "desalinhamento", "más escolhas"],
    descriptionUpright: "Os Enamorados representam amor, harmonia e escolhas importantes. Siga seu coração, mas mantenha clareza sobre seus valores.",
    descriptionReversed: "Quando invertido, pode indicar desequilíbrio em relacionamentos ou conflitos internos sobre decisões importantes.",
  },
  {
    code: "major_07_the_chariot",
    name: "O Carro",
    arcana: "major",
    suit: "none",
    cardIndex: 7,
    keywordsUpright: ["determinação", "vitória", "controle", "força de vontade"],
    keywordsReversed: ["falta de direção", "agressividade", "obstáculos", "perda de controle"],
    descriptionUpright: "O Carro simboliza determinação e vitória através do controle. Mantenha o foco e avance com confiança.",
    descriptionReversed: "Quando invertido, pode indicar falta de direção ou dificuldade em manter o controle sobre a situação.",
  },
  {
    code: "major_08_strength",
    name: "A Força",
    arcana: "major",
    suit: "none",
    cardIndex: 8,
    keywordsUpright: ["coragem", "paciência", "compaixão", "controle interior"],
    keywordsReversed: ["dúvida", "fraqueza", "insegurança", "força bruta"],
    descriptionUpright: "A Força representa coragem interior e domínio gentil. Use compaixão e paciência para superar desafios.",
    descriptionReversed: "Quando invertida, pode indicar dúvidas sobre si mesmo ou uso inadequado de força em situações delicadas.",
  },
  {
    code: "major_09_the_hermit",
    name: "O Eremita",
    arcana: "major",
    suit: "none",
    cardIndex: 9,
    keywordsUpright: ["introspecção", "busca interior", "solidão", "orientação"],
    keywordsReversed: ["isolamento", "reclusão excessiva", "rejeição", "solidão"],
    descriptionUpright: "O Eremita convida à reflexão e busca interior. Afaste-se do ruído para encontrar clareza e sabedoria.",
    descriptionReversed: "Quando invertido, pode indicar isolamento prejudicial ou resistência à autorreflexão necessária.",
  },
  {
    code: "major_10_wheel_of_fortune",
    name: "A Roda da Fortuna",
    arcana: "major",
    suit: "none",
    cardIndex: 10,
    keywordsUpright: ["mudança", "ciclos", "destino", "sorte"],
    keywordsReversed: ["má sorte", "resistência à mudança", "ciclos negativos", "falta de controle"],
    descriptionUpright: "A Roda da Fortuna representa os ciclos da vida e as mudanças inevitáveis. Aceite as transformações com confiança.",
    descriptionReversed: "Quando invertida, pode indicar resistência às mudanças ou período de desafios que requer paciência.",
  },
  {
    code: "major_11_justice",
    name: "A Justiça",
    arcana: "major",
    suit: "none",
    cardIndex: 11,
    keywordsUpright: ["justiça", "verdade", "causa e efeito", "lei"],
    keywordsReversed: ["injustiça", "desonestidade", "falta de responsabilidade", "parcialidade"],
    descriptionUpright: "A Justiça representa equilíbrio, verdade e consequências de ações. Seja honesto e assuma responsabilidade.",
    descriptionReversed: "Quando invertida, pode indicar injustiça, desonestidade ou necessidade de assumir responsabilidades evitadas.",
  },
  {
    code: "major_12_the_hanged_man",
    name: "O Enforcado",
    arcana: "major",
    suit: "none",
    cardIndex: 12,
    keywordsUpright: ["pausa", "rendição", "nova perspectiva", "sacrifício"],
    keywordsReversed: ["estagnação", "adiamento", "resistência", "indecisão"],
    descriptionUpright: "O Enforcado convida a ver as coisas de uma nova perspectiva. Às vezes, pausar é necessário para avançar.",
    descriptionReversed: "Quando invertido, pode indicar estagnação por resistência à mudança ou adiamento de decisões importantes.",
  },
  {
    code: "major_13_death",
    name: "A Morte",
    arcana: "major",
    suit: "none",
    cardIndex: 13,
    keywordsUpright: ["transformação", "fim", "transição", "mudança"],
    keywordsReversed: ["resistência à mudança", "estagnação", "medo", "imobilidade"],
    descriptionUpright: "A Morte simboliza transformação profunda e fim de ciclos. Deixe ir o que não serve mais para abrir espaço ao novo.",
    descriptionReversed: "Quando invertida, indica resistência a mudanças necessárias ou medo de deixar ir situações do passado.",
  },
  {
    code: "major_14_temperance",
    name: "A Temperança",
    arcana: "major",
    suit: "none",
    cardIndex: 14,
    keywordsUpright: ["equilíbrio", "moderação", "paciência", "harmonia"],
    keywordsReversed: ["desequilíbrio", "excesso", "falta de harmonia", "discórdia"],
    descriptionUpright: "A Temperança representa equilíbrio e moderação. Encontre o meio termo e pratique paciência em suas ações.",
    descriptionReversed: "Quando invertida, indica desequilíbrio, excessos ou falta de harmonia que precisam de atenção.",
  },
  {
    code: "major_15_the_devil",
    name: "O Diabo",
    arcana: "major",
    suit: "none",
    cardIndex: 15,
    keywordsUpright: ["apego", "sombra", "vícios", "materialismo"],
    keywordsReversed: ["libertação", "recuperação", "consciência", "desapego"],
    descriptionUpright: "O Diabo representa apegos, ilusões e aspectos sombrios. Reconheça o que o prende para poder se libertar.",
    descriptionReversed: "Quando invertido, indica processo de libertação de padrões negativos e conscientização de hábitos prejudiciais.",
  },
  {
    code: "major_16_the_tower",
    name: "A Torre",
    arcana: "major",
    suit: "none",
    cardIndex: 16,
    keywordsUpright: ["ruptura", "revelação", "mudança súbita", "despertar"],
    keywordsReversed: ["evitação de desastre", "medo de mudança", "resistência", "atraso"],
    descriptionUpright: "A Torre representa mudanças súbitas e revelações que abalam estruturas. Embora difícil, traz oportunidade de reconstrução.",
    descriptionReversed: "Quando invertida, pode indicar resistência a mudanças inevitáveis ou adiamento de transformações necessárias.",
  },
  {
    code: "major_17_the_star",
    name: "A Estrela",
    arcana: "major",
    suit: "none",
    cardIndex: 17,
    keywordsUpright: ["esperança", "inspiração", "serenidade", "renovação"],
    keywordsReversed: ["desesperança", "desânimo", "falta de fé", "desconexão"],
    descriptionUpright: "A Estrela traz esperança, inspiração e renovação. Após a tempestade, surge a calma e novas possibilidades.",
    descriptionReversed: "Quando invertida, indica período de desesperança ou desconexão espiritual que requer cuidado e autocompaixão.",
  },
  {
    code: "major_18_the_moon",
    name: "A Lua",
    arcana: "major",
    suit: "none",
    cardIndex: 18,
    keywordsUpright: ["ilusão", "intuição", "subconsciente", "mistério"],
    keywordsReversed: ["confusão", "medo", "engano revelado", "ansiedade"],
    descriptionUpright: "A Lua representa o reino do subconsciente e da intuição. Nem tudo é o que parece; confie em sua percepção profunda.",
    descriptionReversed: "Quando invertida, indica confusão, medos sendo confrontados ou revelação de enganos anteriores.",
  },
  {
    code: "major_19_the_sun",
    name: "O Sol",
    arcana: "major",
    suit: "none",
    cardIndex: 19,
    keywordsUpright: ["alegria", "sucesso", "vitalidade", "positividade"],
    keywordsReversed: ["negatividade", "tristeza temporária", "ego inflado", "falta de clareza"],
    descriptionUpright: "O Sol irradia alegria, sucesso e vitalidade. É um período de clareza, otimismo e realizações positivas.",
    descriptionReversed: "Quando invertido, pode indicar tristeza temporária ou necessidade de encontrar sua luz interior novamente.",
  },
  {
    code: "major_20_judgement",
    name: "O Julgamento",
    arcana: "major",
    suit: "none",
    cardIndex: 20,
    keywordsUpright: ["renascimento", "despertar", "redenção", "chamado"],
    keywordsReversed: ["autocrítica", "dúvida", "negação", "recusa ao chamado"],
    descriptionUpright: "O Julgamento representa renascimento e despertar espiritual. É hora de avaliar o passado e responder ao seu chamado interior.",
    descriptionReversed: "Quando invertido, indica autocrítica excessiva ou resistência a aceitar mudanças necessárias em sua vida.",
  },
  {
    code: "major_21_the_world",
    name: "O Mundo",
    arcana: "major",
    suit: "none",
    cardIndex: 21,
    keywordsUpright: ["completude", "integração", "realização", "viagem"],
    keywordsReversed: ["incompletude", "falta de encerramento", "atraso", "estagnação"],
    descriptionUpright: "O Mundo representa completude, integração e realização de ciclos. Você alcançou um nível importante de consciência e sucesso.",
    descriptionReversed: "Quando invertido, indica ciclos incompletos ou necessidade de trabalhar mais para alcançar a integração desejada.",
  },
];

// ============================================================
// MINOR ARCANA - WANDS (Paus)
// ============================================================

const wands: TarotCardSeed[] = [
  {
    code: "minor_wands_ace",
    name: "Ás de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 22,
    keywordsUpright: ["inspiração", "novo começo", "potencial", "criatividade"],
    keywordsReversed: ["atrasos", "falta de energia", "bloqueio criativo", "hesitação"],
    descriptionUpright: "O Ás de Paus representa uma centelha de inspiração e novos começos criativos. É hora de iniciar projetos com entusiasmo.",
    descriptionReversed: "Quando invertido, indica atrasos ou bloqueios criativos. A energia para começar pode estar temporariamente baixa.",
  },
  {
    code: "minor_wands_02",
    name: "Dois de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 23,
    keywordsUpright: ["planejamento", "decisões futuras", "progresso", "descoberta"],
    keywordsReversed: ["medo do desconhecido", "falta de planejamento", "indecisão", "surpresas"],
    descriptionUpright: "O Dois de Paus indica planejamento e visão de longo prazo. É momento de considerar suas opções e traçar seu caminho.",
    descriptionReversed: "Quando invertido, sugere medo de dar o próximo passo ou falta de clareza sobre a direção a seguir.",
  },
  {
    code: "minor_wands_03",
    name: "Três de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 24,
    keywordsUpright: ["expansão", "visão", "oportunidades", "progresso"],
    keywordsReversed: ["obstáculos", "atrasos", "frustração", "falta de visão"],
    descriptionUpright: "O Três de Paus simboliza expansão e oportunidades se abrindo. Seus esforços anteriores começam a dar frutos.",
    descriptionReversed: "Quando invertido, indica obstáculos no caminho ou necessidade de ajustar suas expectativas.",
  },
  {
    code: "minor_wands_04",
    name: "Quatro de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 25,
    keywordsUpright: ["celebração", "harmonia", "marco", "lar"],
    keywordsReversed: ["falta de harmonia", "transição", "instabilidade", "celebração adiada"],
    descriptionUpright: "O Quatro de Paus representa celebração e harmonia. É momento de comemorar conquistas e fortalecer laços.",
    descriptionReversed: "Quando invertido, pode indicar falta de harmonia em casa ou celebrações que precisam ser adiadas.",
  },
  {
    code: "minor_wands_05",
    name: "Cinco de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 26,
    keywordsUpright: ["conflito", "competição", "tensão", "desacordo"],
    keywordsReversed: ["evitação de conflito", "resolução", "acordo", "diversidade"],
    descriptionUpright: "O Cinco de Paus representa conflitos e competição. Diferenças de opinião podem surgir, mas trazem crescimento.",
    descriptionReversed: "Quando invertido, indica resolução de conflitos ou tendência a evitar confrontos necessários.",
  },
  {
    code: "minor_wands_06",
    name: "Seis de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 27,
    keywordsUpright: ["vitória", "reconhecimento", "sucesso", "autoconfiança"],
    keywordsReversed: ["ego", "falta de reconhecimento", "fracasso", "orgulho excessivo"],
    descriptionUpright: "O Seis de Paus simboliza vitória e reconhecimento público. Seus esforços estão sendo notados e celebrados.",
    descriptionReversed: "Quando invertido, pode indicar falta de reconhecimento merecido ou excesso de preocupação com a opinião alheia.",
  },
  {
    code: "minor_wands_07",
    name: "Sete de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 28,
    keywordsUpright: ["defesa", "perseverança", "desafio", "competição"],
    keywordsReversed: ["exaustão", "rendição", "sobrecarga", "falta de resistência"],
    descriptionUpright: "O Sete de Paus representa a necessidade de defender sua posição. Perseverança é fundamental diante dos desafios.",
    descriptionReversed: "Quando invertido, indica exaustão na defesa constante ou necessidade de escolher suas batalhas.",
  },
  {
    code: "minor_wands_08",
    name: "Oito de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 29,
    keywordsUpright: ["velocidade", "movimento", "ação rápida", "progresso"],
    keywordsReversed: ["atrasos", "frustração", "espera", "resistência"],
    descriptionUpright: "O Oito de Paus indica movimento rápido e progresso. As coisas estão se acelerando em sua direção.",
    descriptionReversed: "Quando invertido, sugere atrasos frustrantes ou necessidade de paciência em situações que parecem estagnadas.",
  },
  {
    code: "minor_wands_09",
    name: "Nove de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 30,
    keywordsUpright: ["resiliência", "coragem", "persistência", "última resistência"],
    keywordsReversed: ["exaustão", "paranoia", "desistência", "fadiga"],
    descriptionUpright: "O Nove de Paus representa resiliência diante de adversidades. Você chegou longe; não desista agora.",
    descriptionReversed: "Quando invertido, indica exaustão profunda ou medo paralisante. Pode ser hora de buscar apoio.",
  },
  {
    code: "minor_wands_10",
    name: "Dez de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 31,
    keywordsUpright: ["sobrecarga", "responsabilidade", "fardo", "trabalho duro"],
    keywordsReversed: ["delegação", "libertação", "colapso", "alívio"],
    descriptionUpright: "O Dez de Paus simboliza sobrecarga de responsabilidades. Você pode estar carregando mais do que deveria.",
    descriptionReversed: "Quando invertido, indica alívio de fardos ou necessidade urgente de delegar responsabilidades.",
  },
  {
    code: "minor_wands_page",
    name: "Pajem de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 32,
    keywordsUpright: ["entusiasmo", "exploração", "novas ideias", "mensagens"],
    keywordsReversed: ["imaturidade", "falta de direção", "ideias descartadas", "atraso em notícias"],
    descriptionUpright: "O Pajem de Paus traz energia entusiástica e novas possibilidades. Esteja aberto a oportunidades inesperadas.",
    descriptionReversed: "Quando invertido, pode indicar imaturidade nas abordagens ou ideias promissoras que não foram desenvolvidas.",
  },
  {
    code: "minor_wands_knight",
    name: "Cavaleiro de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 33,
    keywordsUpright: ["ação", "aventura", "energia", "paixão"],
    keywordsReversed: ["impulsividade", "atrasos", "frustração", "falta de direção"],
    descriptionUpright: "O Cavaleiro de Paus representa ação apaixonada e aventura. É hora de perseguir seus objetivos com energia.",
    descriptionReversed: "Quando invertido, indica impulsividade ou energia dispersa. Canalize sua paixão de forma mais focada.",
  },
  {
    code: "minor_wands_queen",
    name: "Rainha de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 34,
    keywordsUpright: ["confiança", "determinação", "carisma", "independência"],
    keywordsReversed: ["agressividade", "ciúme", "exigência", "dominação"],
    descriptionUpright: "A Rainha de Paus representa confiança, carisma e determinação. Lidere com coragem e inspire os outros.",
    descriptionReversed: "Quando invertida, pode indicar tendência à agressividade ou controle excessivo nas situações.",
  },
  {
    code: "minor_wands_king",
    name: "Rei de Paus",
    arcana: "minor",
    suit: "wands",
    cardIndex: 35,
    keywordsUpright: ["liderança", "visão", "empreendedorismo", "honra"],
    keywordsReversed: ["impulsividade", "autoritarismo", "expectativas irreais", "arrogância"],
    descriptionUpright: "O Rei de Paus simboliza liderança visionária e ação decisiva. Use sua influência para criar impacto positivo.",
    descriptionReversed: "Quando invertido, pode indicar liderança autoritária ou tendência a decisões impulsivas sem consideração.",
  },
];

// ============================================================
// MINOR ARCANA - CUPS (Copas)
// ============================================================

const cups: TarotCardSeed[] = [
  {
    code: "minor_cups_ace",
    name: "Ás de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 36,
    keywordsUpright: ["amor", "emoções", "intuição", "novo relacionamento"],
    keywordsReversed: ["bloqueio emocional", "vazio", "repressão", "amor não correspondido"],
    descriptionUpright: "O Ás de Copas representa novos começos emocionais e abertura do coração. Amor e conexões profundas estão chegando.",
    descriptionReversed: "Quando invertido, indica bloqueios emocionais ou dificuldade em se abrir para novas conexões.",
  },
  {
    code: "minor_cups_02",
    name: "Dois de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 37,
    keywordsUpright: ["parceria", "união", "conexão", "atração mútua"],
    keywordsReversed: ["desequilíbrio", "separação", "incompatibilidade", "desconfiança"],
    descriptionUpright: "O Dois de Copas simboliza parceria harmoniosa e conexão profunda. Relacionamentos equilibrados estão em destaque.",
    descriptionReversed: "Quando invertido, pode indicar desequilíbrio na relação ou necessidade de trabalhar a compatibilidade.",
  },
  {
    code: "minor_cups_03",
    name: "Três de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 38,
    keywordsUpright: ["celebração", "amizade", "comunidade", "alegria compartilhada"],
    keywordsReversed: ["excesso", "fofoca", "isolamento", "superficialidade"],
    descriptionUpright: "O Três de Copas representa celebração entre amigos e alegria compartilhada. É tempo de conexões sociais felizes.",
    descriptionReversed: "Quando invertido, pode indicar excessos sociais ou relacionamentos superficiais que não satisfazem.",
  },
  {
    code: "minor_cups_04",
    name: "Quatro de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 39,
    keywordsUpright: ["contemplação", "apatia", "reavaliação", "descontentamento"],
    keywordsReversed: ["novas oportunidades", "consciência", "aceitação", "motivação"],
    descriptionUpright: "O Quatro de Copas indica período de contemplação e possível insatisfação. Avalie o que realmente deseja.",
    descriptionReversed: "Quando invertido, sugere abertura para novas oportunidades anteriormente ignoradas.",
  },
  {
    code: "minor_cups_05",
    name: "Cinco de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 40,
    keywordsUpright: ["perda", "luto", "arrependimento", "desapontamento"],
    keywordsReversed: ["aceitação", "superação", "perdão", "seguir em frente"],
    descriptionUpright: "O Cinco de Copas representa perda e luto. É natural sentir tristeza, mas há ainda copos em pé.",
    descriptionReversed: "Quando invertido, indica processo de aceitação e capacidade de seguir em frente após perdas.",
  },
  {
    code: "minor_cups_06",
    name: "Seis de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 41,
    keywordsUpright: ["nostalgia", "memórias", "inocência", "generosidade"],
    keywordsReversed: ["apego ao passado", "ingenuidade", "infantilidade", "falta de progresso"],
    descriptionUpright: "O Seis de Copas evoca nostalgia e memórias felizes. Reconecte-se com a inocência e generosidade do coração.",
    descriptionReversed: "Quando invertido, pode indicar apego excessivo ao passado ou dificuldade em amadurecer.",
  },
  {
    code: "minor_cups_07",
    name: "Sete de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 42,
    keywordsUpright: ["escolhas", "fantasia", "ilusão", "sonhos"],
    keywordsReversed: ["clareza", "decisão", "realismo", "foco"],
    descriptionUpright: "O Sete de Copas representa múltiplas escolhas e fantasias. Cuidado com ilusões; nem todas as opções são reais.",
    descriptionReversed: "Quando invertido, indica clareza chegando e capacidade de fazer escolhas realistas.",
  },
  {
    code: "minor_cups_08",
    name: "Oito de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 43,
    keywordsUpright: ["partida", "busca", "abandono", "desapego"],
    keywordsReversed: ["medo de partir", "estagnação", "aceitação", "evitação"],
    descriptionUpright: "O Oito de Copas simboliza a decisão de partir em busca de algo mais significativo. Às vezes, ir embora é necessário.",
    descriptionReversed: "Quando invertido, indica dificuldade em deixar situações que não satisfazem ou medo de mudanças.",
  },
  {
    code: "minor_cups_09",
    name: "Nove de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 44,
    keywordsUpright: ["satisfação", "realização de desejos", "contentamento", "gratidão"],
    keywordsReversed: ["insatisfação", "materialismo", "excesso", "desejos não realizados"],
    descriptionUpright: "O Nove de Copas é a carta dos desejos realizados. Aprecie suas conquistas e pratique gratidão.",
    descriptionReversed: "Quando invertido, pode indicar insatisfação apesar de conquistas ou foco excessivo em desejos materiais.",
  },
  {
    code: "minor_cups_10",
    name: "Dez de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 45,
    keywordsUpright: ["harmonia familiar", "felicidade", "realização emocional", "paz"],
    keywordsReversed: ["desarmonia", "conflitos familiares", "valores diferentes", "ruptura"],
    descriptionUpright: "O Dez de Copas representa a felicidade completa e harmonia familiar. É o ápice da realização emocional.",
    descriptionReversed: "Quando invertido, indica desarmonia familiar ou valores em conflito que precisam ser resolvidos.",
  },
  {
    code: "minor_cups_page",
    name: "Pajem de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 46,
    keywordsUpright: ["criatividade", "intuição", "mensagens emocionais", "sonhador"],
    keywordsReversed: ["imaturidade emocional", "bloqueio criativo", "más notícias", "escapismo"],
    descriptionUpright: "O Pajem de Copas traz mensagens de intuição e criatividade. Esteja aberto a inspirações do coração.",
    descriptionReversed: "Quando invertido, pode indicar imaturidade emocional ou tendência ao escapismo.",
  },
  {
    code: "minor_cups_knight",
    name: "Cavaleiro de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 47,
    keywordsUpright: ["romance", "charme", "imaginação", "proposta"],
    keywordsReversed: ["desilusão", "temperamento", "irrealismo", "manipulação"],
    descriptionUpright: "O Cavaleiro de Copas representa romance e ofertas do coração. Propostas e convites emocionais estão chegando.",
    descriptionReversed: "Quando invertido, indica desilusão romântica ou expectativas irrealistas em relacionamentos.",
  },
  {
    code: "minor_cups_queen",
    name: "Rainha de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 48,
    keywordsUpright: ["compaixão", "intuição", "nutrição emocional", "sensibilidade"],
    keywordsReversed: ["codependência", "martírio", "manipulação emocional", "insegurança"],
    descriptionUpright: "A Rainha de Copas representa compaixão profunda e intuição aguçada. Cuide de si e dos outros com amor.",
    descriptionReversed: "Quando invertida, pode indicar tendência à codependência ou manipulação através das emoções.",
  },
  {
    code: "minor_cups_king",
    name: "Rei de Copas",
    arcana: "minor",
    suit: "cups",
    cardIndex: 49,
    keywordsUpright: ["equilíbrio emocional", "diplomacia", "sabedoria", "controle"],
    keywordsReversed: ["manipulação", "frieza", "repressão", "desequilíbrio"],
    descriptionUpright: "O Rei de Copas simboliza maturidade emocional e equilíbrio. Lidere com o coração e a mente em harmonia.",
    descriptionReversed: "Quando invertido, indica repressão emocional ou uso manipulativo de habilidades emocionais.",
  },
];

// ============================================================
// MINOR ARCANA - SWORDS (Espadas)
// ============================================================

const swords: TarotCardSeed[] = [
  {
    code: "minor_swords_ace",
    name: "Ás de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 50,
    keywordsUpright: ["clareza", "verdade", "novo pensamento", "avanço mental"],
    keywordsReversed: ["confusão", "caos", "hostilidade", "ideias obscuras"],
    descriptionUpright: "O Ás de Espadas representa clareza mental e novos insights. A verdade está se revelando com força.",
    descriptionReversed: "Quando invertido, indica confusão mental ou uso negativo do intelecto.",
  },
  {
    code: "minor_swords_02",
    name: "Dois de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 51,
    keywordsUpright: ["indecisão", "impasse", "negação", "escolhas difíceis"],
    keywordsReversed: ["confusão", "sobrecarga de informação", "decisão", "ver a verdade"],
    descriptionUpright: "O Dois de Espadas indica impasse e dificuldade em decidir. Informação importante pode estar sendo bloqueada.",
    descriptionReversed: "Quando invertido, pode indicar que a verdade finalmente está sendo vista ou decisão sendo tomada.",
  },
  {
    code: "minor_swords_03",
    name: "Três de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 52,
    keywordsUpright: ["dor", "coração partido", "luto", "tristeza"],
    keywordsReversed: ["recuperação", "perdão", "superação", "liberação"],
    descriptionUpright: "O Três de Espadas representa dor emocional profunda. É preciso processar a tristeza para seguir em frente.",
    descriptionReversed: "Quando invertido, indica início da recuperação e processo de perdão e cura.",
  },
  {
    code: "minor_swords_04",
    name: "Quatro de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 53,
    keywordsUpright: ["descanso", "recuperação", "contemplação", "paz"],
    keywordsReversed: ["exaustão", "inquietação", "burnout", "retorno à ação"],
    descriptionUpright: "O Quatro de Espadas convida ao descanso e recuperação. Faça uma pausa para restaurar suas energias.",
    descriptionReversed: "Quando invertido, indica inquietação ou resistência ao descanso necessário.",
  },
  {
    code: "minor_swords_05",
    name: "Cinco de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 54,
    keywordsUpright: ["conflito", "derrota", "vitória vazia", "tensão"],
    keywordsReversed: ["reconciliação", "perdão", "seguir em frente", "aceitação"],
    descriptionUpright: "O Cinco de Espadas representa conflitos e possíveis vitórias que deixam um gosto amargo. Avalie se vale a pena.",
    descriptionReversed: "Quando invertido, indica processo de reconciliação ou decisão de não perpetuar conflitos.",
  },
  {
    code: "minor_swords_06",
    name: "Seis de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 55,
    keywordsUpright: ["transição", "mudança", "viagem", "deixar para trás"],
    keywordsReversed: ["resistência", "bagagem emocional", "estagnação", "retorno"],
    descriptionUpright: "O Seis de Espadas simboliza transição para águas mais calmas. Você está deixando tempos difíceis para trás.",
    descriptionReversed: "Quando invertido, indica resistência a mudanças necessárias ou bagagem emocional que dificulta a transição.",
  },
  {
    code: "minor_swords_07",
    name: "Sete de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 56,
    keywordsUpright: ["engano", "estratégia", "furtividade", "prudência"],
    keywordsReversed: ["exposição", "confissão", "consciência", "arrependimento"],
    descriptionUpright: "O Sete de Espadas indica necessidade de estratégia ou possível engano na situação. Aja com prudência.",
    descriptionReversed: "Quando invertido, pode indicar exposição de segredos ou momento de honestidade e confissão.",
  },
  {
    code: "minor_swords_08",
    name: "Oito de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 57,
    keywordsUpright: ["restrição", "impotência", "vitimização", "prisão mental"],
    keywordsReversed: ["libertação", "nova perspectiva", "autoconfiança", "empoderamento"],
    descriptionUpright: "O Oito de Espadas representa sensação de estar preso. As restrições podem ser mais mentais que reais.",
    descriptionReversed: "Quando invertido, indica libertação de padrões limitantes e recuperação da autoconfiança.",
  },
  {
    code: "minor_swords_09",
    name: "Nove de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 58,
    keywordsUpright: ["ansiedade", "pesadelos", "preocupação", "culpa"],
    keywordsReversed: ["esperança", "superação do medo", "recuperação", "busca de ajuda"],
    descriptionUpright: "O Nove de Espadas representa ansiedade e preocupações que tiram o sono. Os medos podem parecer maiores do que são.",
    descriptionReversed: "Quando invertido, indica início da superação de ansiedades ou decisão de buscar ajuda.",
  },
  {
    code: "minor_swords_10",
    name: "Dez de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 59,
    keywordsUpright: ["fim doloroso", "traição", "perda", "rock bottom"],
    keywordsReversed: ["recuperação", "renascimento", "inevitável", "resistência"],
    descriptionUpright: "O Dez de Espadas marca um fim doloroso mas definitivo. Do fundo do poço, só resta subir.",
    descriptionReversed: "Quando invertido, indica início da recuperação ou resistência a aceitar que algo terminou.",
  },
  {
    code: "minor_swords_page",
    name: "Pajem de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 60,
    keywordsUpright: ["curiosidade", "novas ideias", "comunicação", "vigilância"],
    keywordsReversed: ["fofoca", "imprudência", "manipulação", "falta de planejamento"],
    descriptionUpright: "O Pajem de Espadas traz curiosidade intelectual e novas ideias. Esteja atento a informações importantes.",
    descriptionReversed: "Quando invertido, pode indicar uso irresponsável da comunicação ou falta de preparo.",
  },
  {
    code: "minor_swords_knight",
    name: "Cavaleiro de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 61,
    keywordsUpright: ["ação rápida", "ambição", "determinação", "franqueza"],
    keywordsReversed: ["impulsividade", "impaciência", "agressividade", "falta de tato"],
    descriptionUpright: "O Cavaleiro de Espadas representa ação decisiva e mente afiada. Avance com determinação, mas com sabedoria.",
    descriptionReversed: "Quando invertido, indica impulsividade prejudicial ou comunicação agressiva demais.",
  },
  {
    code: "minor_swords_queen",
    name: "Rainha de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 62,
    keywordsUpright: ["clareza", "independência", "percepção", "honestidade direta"],
    keywordsReversed: ["frieza", "crueldade", "amargor", "pessimismo"],
    descriptionUpright: "A Rainha de Espadas representa clareza mental e independência. Sua honestidade e percepção são suas forças.",
    descriptionReversed: "Quando invertida, pode indicar frieza excessiva ou uso da inteligência para ferir.",
  },
  {
    code: "minor_swords_king",
    name: "Rei de Espadas",
    arcana: "minor",
    suit: "swords",
    cardIndex: 63,
    keywordsUpright: ["autoridade intelectual", "verdade", "clareza", "ética"],
    keywordsReversed: ["manipulação", "tirania", "frieza", "abuso de poder"],
    descriptionUpright: "O Rei de Espadas simboliza autoridade intelectual e julgamento justo. Use sua mente a serviço da verdade.",
    descriptionReversed: "Quando invertido, indica uso manipulativo da inteligência ou abuso de poder intelectual.",
  },
];

// ============================================================
// MINOR ARCANA - PENTACLES (Ouros)
// ============================================================

const pentacles: TarotCardSeed[] = [
  {
    code: "minor_pentacles_ace",
    name: "Ás de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 64,
    keywordsUpright: ["oportunidade", "prosperidade", "novo empreendimento", "abundância"],
    keywordsReversed: ["oportunidade perdida", "falta de planejamento", "escassez", "instabilidade"],
    descriptionUpright: "O Ás de Ouros representa novas oportunidades de prosperidade. Fundações sólidas estão sendo plantadas.",
    descriptionReversed: "Quando invertido, indica oportunidades perdidas ou falta de base sólida para novos projetos.",
  },
  {
    code: "minor_pentacles_02",
    name: "Dois de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 65,
    keywordsUpright: ["equilíbrio", "adaptação", "prioridades", "flexibilidade"],
    keywordsReversed: ["desequilíbrio", "desorganização", "sobrecarga", "má administração"],
    descriptionUpright: "O Dois de Ouros indica necessidade de equilibrar múltiplas responsabilidades. Adaptabilidade é fundamental.",
    descriptionReversed: "Quando invertido, sugere desequilíbrio financeiro ou dificuldade em administrar compromissos.",
  },
  {
    code: "minor_pentacles_03",
    name: "Três de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 66,
    keywordsUpright: ["trabalho em equipe", "habilidade", "colaboração", "aprendizado"],
    keywordsReversed: ["falta de trabalho em equipe", "desalinhamento", "mediocridade", "conflitos"],
    descriptionUpright: "O Três de Ouros representa colaboração e desenvolvimento de habilidades. O trabalho em equipe traz resultados.",
    descriptionReversed: "Quando invertido, indica falta de cooperação ou trabalho que não atende aos padrões desejados.",
  },
  {
    code: "minor_pentacles_04",
    name: "Quatro de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 67,
    keywordsUpright: ["segurança", "conservadorismo", "controle", "estabilidade"],
    keywordsReversed: ["generosidade", "abertura", "liberação", "insegurança financeira"],
    descriptionUpright: "O Quatro de Ouros indica desejo de segurança e controle material. Proteja seus recursos, mas sem rigidez.",
    descriptionReversed: "Quando invertido, pode indicar liberação de apegos materiais ou insegurança financeira.",
  },
  {
    code: "minor_pentacles_05",
    name: "Cinco de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 68,
    keywordsUpright: ["dificuldade", "perda", "isolamento", "preocupação material"],
    keywordsReversed: ["recuperação", "melhora", "ajuda chegando", "superação"],
    descriptionUpright: "O Cinco de Ouros representa dificuldades materiais e sensação de exclusão. Ajuda pode estar mais perto do que parece.",
    descriptionReversed: "Quando invertido, indica recuperação de dificuldades ou abertura para receber ajuda.",
  },
  {
    code: "minor_pentacles_06",
    name: "Seis de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 69,
    keywordsUpright: ["generosidade", "caridade", "dar e receber", "equilíbrio"],
    keywordsReversed: ["dívidas", "exploração", "expectativas", "generosidade interesseira"],
    descriptionUpright: "O Seis de Ouros representa generosidade e equilíbrio no dar e receber. Compartilhe sua abundância.",
    descriptionReversed: "Quando invertido, pode indicar desequilíbrio nas trocas ou generosidade com segundas intenções.",
  },
  {
    code: "minor_pentacles_07",
    name: "Sete de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 70,
    keywordsUpright: ["paciência", "investimento", "avaliação", "crescimento lento"],
    keywordsReversed: ["impaciência", "falta de recompensa", "maus investimentos", "frustração"],
    descriptionUpright: "O Sete de Ouros indica tempo de avaliação e paciência. Os frutos do seu trabalho estão amadurecendo.",
    descriptionReversed: "Quando invertido, sugere impaciência com resultados ou necessidade de reavaliar investimentos.",
  },
  {
    code: "minor_pentacles_08",
    name: "Oito de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 71,
    keywordsUpright: ["aprendizado", "maestria", "dedicação", "qualidade"],
    keywordsReversed: ["perfecionismo", "falta de foco", "trabalho sem propósito", "atalhos"],
    descriptionUpright: "O Oito de Ouros representa dedicação ao aprendizado e aperfeiçoamento. Continue refinando suas habilidades.",
    descriptionReversed: "Quando invertido, indica perfecionismo paralisante ou trabalho sem significado.",
  },
  {
    code: "minor_pentacles_09",
    name: "Nove de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 72,
    keywordsUpright: ["abundância", "luxo", "independência", "autodisciplina"],
    keywordsReversed: ["excesso de trabalho", "superficialidade", "solidão", "dependência"],
    descriptionUpright: "O Nove de Ouros representa abundância conquistada e independência financeira. Aprecie os frutos do seu trabalho.",
    descriptionReversed: "Quando invertido, pode indicar excesso de foco no material ou solidão apesar do sucesso.",
  },
  {
    code: "minor_pentacles_10",
    name: "Dez de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 73,
    keywordsUpright: ["riqueza", "herança", "família", "legado"],
    keywordsReversed: ["conflitos familiares", "perda financeira", "disputas", "instabilidade"],
    descriptionUpright: "O Dez de Ouros representa riqueza duradoura e legado familiar. A prosperidade beneficia gerações.",
    descriptionReversed: "Quando invertido, indica conflitos familiares relacionados a finanças ou herança instável.",
  },
  {
    code: "minor_pentacles_page",
    name: "Pajem de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 74,
    keywordsUpright: ["aprendizado", "oportunidade", "novos estudos", "mensagens práticas"],
    keywordsReversed: ["falta de progresso", "procrastinação", "oportunidades perdidas", "imaturidade"],
    descriptionUpright: "O Pajem de Ouros traz oportunidades de aprendizado e crescimento prático. Invista em suas habilidades.",
    descriptionReversed: "Quando invertido, indica procrastinação ou oportunidades de crescimento não aproveitadas.",
  },
  {
    code: "minor_pentacles_knight",
    name: "Cavaleiro de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 75,
    keywordsUpright: ["trabalho duro", "responsabilidade", "confiabilidade", "eficiência"],
    keywordsReversed: ["estagnação", "perfeccionismo", "falta de visão", "teimosia"],
    descriptionUpright: "O Cavaleiro de Ouros representa dedicação metódica e trabalho consistente. O progresso virá através da persistência.",
    descriptionReversed: "Quando invertido, indica rotina excessiva ou falta de flexibilidade nos métodos.",
  },
  {
    code: "minor_pentacles_queen",
    name: "Rainha de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 76,
    keywordsUpright: ["nutrição", "praticidade", "segurança", "abundância"],
    keywordsReversed: ["desequilíbrio trabalho-vida", "dependência", "inveja", "insegurança"],
    descriptionUpright: "A Rainha de Ouros representa nutrição prática e abundância estável. Cuide do seu bem-estar e daqueles ao redor.",
    descriptionReversed: "Quando invertida, pode indicar desequilíbrio entre dar e receber ou insegurança material.",
  },
  {
    code: "minor_pentacles_king",
    name: "Rei de Ouros",
    arcana: "minor",
    suit: "pentacles",
    cardIndex: 77,
    keywordsUpright: ["riqueza", "negócios", "liderança", "segurança"],
    keywordsReversed: ["materialismo", "ganância", "possessividade", "má gestão"],
    descriptionUpright: "O Rei de Ouros simboliza sucesso material e liderança nos negócios. Use sua prosperidade com sabedoria.",
    descriptionReversed: "Quando invertido, indica materialismo excessivo ou má gestão de recursos.",
  },
];

// ============================================================
// COMBINED DECK
// ============================================================

export const TAROT_DECK: TarotCardSeed[] = [
  ...majorArcana,
  ...wands,
  ...cups,
  ...swords,
  ...pentacles,
];

export const DECK_METADATA = {
  name: "Tarot Clássico",
  locale: "pt-BR",
  totalCards: 78,
  majorArcanaCount: 22,
  minorArcanaCount: 56,
};
